# Generated by Django 4.2.3 on 2023-08-09 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("device_transaction", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="Device",
            new_name="device",
        ),
    ]
