# Generated by Django 4.2.3 on 2023-08-04 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("device_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="ports",
            new_name="device_ports",
        ),
    ]
