# Generated by Django 4.2.3 on 2023-08-04 03:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("device_tracker", "0002_rename_ports_device_device_ports"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="device_ports",
            new_name="ports",
        ),
    ]
