# Generated by Django 4.2.3 on 2023-08-04 04:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("device_tracker", "0004_rename_ports_device_device_ports"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="ip",
            new_name="device_ip",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="name",
            new_name="device_name",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="serial_number",
            new_name="device_serial_number",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="status",
            new_name="device_status",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="type_device",
            new_name="device_type",
        ),
    ]
